# Generated by Django 3.2.4 on 2021-06-18 02:17

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Dept', models.CharField(max_length=50)),
                ('Date_of_birth', models.DateTimeField(verbose_name=django.db.models.fields.DateTimeField)),
                ('contact', models.TextField(max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
